### ISSUE TITLE
Squash optargs into one job

### ISSUE THREAD

**Issue by ledif** [ledif/dimebox#42]
We can provide the ability to squash experiments that normally would contain many jobs to group them by processor count. For example, if we have:

``` yml
optargs:
  a: [1, 2, 3]
  b: [7, 8, 9]
```

we can create 1 job that runs all 9 configurations instead of creating 9 separate jobs.
