### ISSUE TITLE
Support for generating jobs using pairs of arguments instead of cross product

### ISSUE THREAD

**Issue by ledif** [ledif/dimebox#43]
Currently, the `optargs` field is used in expfiles to generate a cross product of arguments. For example, if we have:

```yml
optargs:
  a: [0,1]
  b: [20,30]
```
We would generate 4 total jobs, with (a,b) pairs of (0,20), (0,30), (1,20), (1,30). Instead, we may only want to generate pair-wise configurations:

```yml
pairargs:
  a: [0,1]
  b: [20,30]
```

where we will generate only (0,20) and (1,30).

We may also want to rename `optargs` to `crossargs` to better illustrate its intention.
